.TH "smf-spamq" "1" "29 Apr 2010" "" ""

.SH "NAME"
smf-spamq - spmfilter-spamassassin quarantine
.SH "SYNOPSIS"
.P
\fBsmf-spamq\fR \fB-q \fIquarantine_dir\fR

.SH "DESCRIPTION"
.P
The \fBsmf-spamq\fR(1) command displays all messages in the spam quarantine.

.SH "OPTIONS"
.P
The following command-line options are implemented:
.IP "\fB-d \fIquarantine_dir\fR (or --quarantine)"
Define path to spmfilter-spamassassin quarantine directory.

.IP "\fB-?\fR (or --help)"
Print smf-spamq usage.

.SH "SEE ALSO"
.P
spmfilter-spamassassin(1), smf-spamctl(1), spmfilter.conf(5), spmfilter(1)

.SH "AUTHOR(S)"
.P
spmfilter-spamassassin was written by Axel Steiner <ast@treibsand.com>